Apply Machine Learning Exercise
In this exercise, you'll be given a real-world situation where a radiologist's worklist needs to be prioritized. In this scenario, you have a radiologist who works in a very busy emergency department in a major city. They are often getting hundreds of emergency images that need to be read every day, and there is no prioritization around those images because they come in through the emergency department, so everything is marked as "urgent." In the current setting, radiologists read these images in a first-in-first-out queue, where all images are simply read in the order that they come in. From a clinical perspective, you know that some urgent cases are truly more urgent than others. From your research in interviewing emergency doctors and radiologists, you have identified that two of the most urgent types of findings on an image are a brain bleed and an aortic dissection. Both of these problems can lead to patient death within minutes, but they can only be detected on imaging, so it is critical these images are read ASAP.

You have used deep learning to create two classification algorithms, one for the detection of brain bleeds on head CT images, and one for the detection of aortic dissection on chest x-ray images. Now, you need to figure out how to integrate these algorithms into the radiologist's workflow so that they are most helpful clinically.

In this exercise you'll be given the following:

A list of images that have come in through the ED in order of patient arrival
Probabilities of 'brain bleed' for each image, as determined by one of your deep learning algorithms
Probabilities of 'aortic dissection' for each image, as determined by one of your deep learning algorithms
You will need to do the following:

Calculate the amount of time it will take before each image is read by the radiologist, given the patient arrival queue, assuming each image takes 6 minutes to read
Implement a heuristic that uses the probabilities returned by your two algorithms to re-order the priority read list, assuming that brain bleeds and aortic dissections are equally urgent
Calculate the time delta for each image between the initial and the re-ordered priority reads
Answer the following questions based on your reprioritization:

If your algorithm's goal was to have brain bleeds read 30 minutes faster, how did it do?
If your algorithm's goal was to have aortic dissections read 15 minutes faster, how did it do?
Were there any cases where your algorithm made it worse for patients who needed an ASAP read? Could anything have been done about this?

In [49]:
import pandas as pd
import numpy as np

## Worklist prioritization: Emergency Setting

In [50]:
## First, read in the file of the current worklist with the probabilities that your two algorithms have
## generated for the two types of findings you're most concerned with:

worklist = pd.read_csv('probabilities.csv')

In [51]:
worklist.head()

   Image_Type  Brain_bleed_probability  Aortic_dissection_probability
0  chest_xray                      0.0                           0.05
1  chest_xray                      0.0                           0.17
2  chest_xray                      0.0                           0.00
3  chest_xray                      0.0                           0.04
4  wrist_xray                      0.0                           0.00

In [52]:
worklist["time_given"] = np.arange(6, 6*100, 6)

In [53]:
worklist.shape

(99, 4)

In [56]:
worklist.head()

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,time_given,Probability_compared
0,chest_xray,0.0,0.05,6,0
1,chest_xray,0.0,0.17,12,1
2,chest_xray,0.0,0.00,18,2
3,chest_xray,0.0,0.04,24,3
4,wrist_xray,0.0,0.00,30,4

In [67]:
worklist.tail()

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,time_given,Probability_compared
94,chest_xray,0.00,0.06,570,0
95,head_ct,0.90,0.00,576,0
96,head_ct,0.45,0.00,582,0
97,femur_xray,0.00,0.00,588,0
98,chest_xray,0.00,0.00,594,0

In [79]:
for i in range(0, 99):
    if worklist.iloc[i, 2] <= worklist.iloc[i, 1]:
        worklist.iloc[i, 4] = worklist.iloc[i, 1]
    else:
        worklist.iloc[i, 4] = worklist.iloc[i, 2]

In [80]:
worklist.head()

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,time_given,Probability_compared
0,chest_xray,0.0,0.05,6,0.05
1,chest_xray,0.0,0.17,12,0.17
2,chest_xray,0.0,0.00,18,0.00
3,chest_xray,0.0,0.04,24,0.04
4,wrist_xray,0.0,0.00,30,0.00

In [89]:
worklist = worklist.sort_values('Probability_compared', ascending = False)
worklist.head()

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,time_given,Probability_compared
25,head_ct,0.99,0.00,156,0.99
15,chest_xray,0.00,0.95,96,0.95
10,chest_xray,0.00,0.94,66,0.94
75,chest_xray,0.00,0.93,456,0.93
47,chest_xray,0.00,0.93,288,0.93

In [90]:
worklist["time_new"] = np.arange(6, 6*100, 6)

In [92]:
worklist.tail()

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,time_given,Probability_compared,time_new
7,femur_xray,0.0,0.0,48,0.0,570
4,wrist_xray,0.0,0.0,30,0.0,576
2,chest_xray,0.0,0.0,18,0.0,582
97,femur_xray,0.0,0.0,588,0.0,588
98,chest_xray,0.0,0.0,594,0.0,594

In [94]:
worklist["time_delta"] = worklist["time_given"] - worklist["time_new"]
worklist.head()

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,time_given,Probability_compared,time_new,time_delta
25,head_ct,0.99,0.00,156,0.99,6,150
15,chest_xray,0.00,0.95,96,0.95,12,84
10,chest_xray,0.00,0.94,66,0.94,18,48
75,chest_xray,0.00,0.93,456,0.93,24,432
47,chest_xray,0.00,0.93,288,0.93,30,258

In [99]:
# If your algorithm's goal was to have brain bleeds read 30 minutes faster, how did it do?
worklist[(worklist.time_delta > 30) & (worklist.Image_Type == 'head_ct')].reset_index()

,index,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,time_given,Probability_compared,time_new,time_delta
0,25,head_ct,0.99,0.0,156,0.99,6,150
1,84,head_ct,0.91,0.0,510,0.91,36,474
2,95,head_ct,0.90,0.0,576,0.90,42,534
3,42,head_ct,0.89,0.0,258,0.89,48,210
4,59,head_ct,0.89,0.0,360,0.89,54,306
5,89,head_ct,0.78,0.0,540,0.78,96,444
6,39,head_ct,0.77,0.0,240,0.77,102,138
7,45,head_ct,0.75,0.0,276,0.75,108,168
8,76,head_ct,0.69,0.0,462,0.69,144,318
9,96,head_ct,0.45,0.0,582,0.45,198,384
10,78,head_ct,0.44,0.0,474,0.44,204,270
11,56,head_ct,0.22,0.0,342,0.22,258,84
12,68,head_ct,0.07,0.0,414,0.07,324,90
13,82,head_ct,0.05,0.0,498,0.05,336,162

In [100]:
# There are about 14 cts 
# The last three cts have a probability of less than 0.4

In [101]:
# If your algorithm's goal was to have aortic dissections read 15 minutes faster, how did it do?
worklist[(worklist.time_delta > 15) & (worklist.Image_Type == 'chest_xray')].reset_index()

,index,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,time_given,Probability_compared,time_new,time_delta
0,15,chest_xray,0.0,0.95,96,0.95,12,84
1,10,chest_xray,0.0,0.94,66,0.94,18,48
2,75,chest_xray,0.0,0.93,456,0.93,24,432
3,47,chest_xray,0.0,0.93,288,0.93,30,258
4,48,chest_xray,0.0,0.84,294,0.84,60,234
5,38,chest_xray,0.0,0.83,234,0.83,66,168
6,87,chest_xray,0.0,0.82,528,0.82,72,456
7,62,chest_xray,0.0,0.82,378,0.82,78,300
8,44,chest_xray,0.0,0.81,270,0.81,84,186
9,85,chest_xray,0.0,0.79,516,0.79,90,426
10,81,chest_xray,0.0,0.73,492,0.73,114,378
11,53,chest_xray,0.0,0.72,324,0.72,120,204
12,27,chest_xray,0.0,0.71,168,0.71,126,42
13,51,chest_xray,0.0,0.71,312,0.71,132,180
14,66,chest_xray,0.0,0.70,402,0.70,138,264
15,46,chest_xray,0.0,0.60,282,0.60,168,114
16,69,chest_xray,0.0,0.60,420,0.60,174,246
17,93,chest_xray,0.0,0.49,564,0.49,186,378
18,70,chest_xray,0.0,0.48,426,0.48,192,234
19,72,chest_xray,0.0,0.38,438,0.38,210,228
20,92,chest_xray,0.0,0.26,558,0.26,234,324
21,61,chest_xray,0.0,0.26,372,0.26,240,132
22,74,chest_xray,0.0,0.15,450,0.15,288,162
23,90,chest_xray,0.0,0.15,546,0.15,294,252
24,79,chest_xray,0.0,0.11,480,0.11,306,174
25,83,chest_xray,0.0,0.11,504,0.11,312,192
26,94,chest_xray,0.0,0.06,570,0.06,330,240
27,77,chest_xray,0.0,0.04,468,0.04,366,102

In [102]:
# There are about 28 cts
# Nine cts have probabilities less than 0.4

In [104]:
# Were there any cases where your algorithm made it worse for patients who needed an ASAP read?
# Could anything have been done about this?

In [106]:
worklist[(worklist.time_new > worklist.time_given) & (worklist.Probability_compared > 0.40)].reset_index()

,index,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,time_given,Probability_compared,time_new,time_delta
0,18,head_ct,0.67,0.00,114,0.67,150,-36
1,5,chest_xray,0.00,0.67,36,0.67,156,-120
2,14,chest_xray,0.00,0.49,90,0.49,180,-90

In [107]:
# There are about three cases where the prioritized queue actually delayed the read rather than speed it up.

In [109]:
worklist.head()

,Image_Type,Brain_bleed_probability,Aortic_dissection_probability,time_given,Probability_compared,time_new,time_delta
25,head_ct,0.99,0.00,156,0.99,6,150
15,chest_xray,0.00,0.95,96,0.95,12,84
10,chest_xray,0.00,0.94,66,0.94,18,48
75,chest_xray,0.00,0.93,456,0.93,24,432
47,chest_xray,0.00,0.93,288,0.93,30,258